language: node_js
sudo: required
node_js:
- 8
os: linux
cache:
  yarn: true
branches:
  only:
  - master
  - dev
install:
- |
    yarn install
script:
- |
    npm run lint && npm run test
after_success:
- |
    npm run coverall
